name: ReAbility
version: '2.2'
main: org.kkaemok.reAbility.ReAbility
api-version: '1.21'
depend: [LuckPerms, ProtocolLib]

commands:
  능력:
    description: 능력 관련 커맨드를 실행합니다.
    usage: /능력 <뽑기|설명|리로드|리스트|주인> <B1|B2|C|A|S>
  유지권:
    description: 능력 유지권을 지급합니다.
    usage: /유지권 <일수>
  방어막:
    description: 크로노스 전용 방어막을 사용합니다.
    usage: /방어막
  rtp:
    description: 랜덤 텔레포트를 실행합니다.
    usage: /rtp
  tpa:
    description: 플레이어에게 텔레포트를 요청하거나 수락, 거절합니다.
    usage: /tpa <플레이어|수락|거절>
  길드:
    description: 길드 관리 명령어입니다.
    usage: /길드 <생성|요청|수락|탈퇴|확장> <플레이어|이름|길드명> <색상>
  길드챗:
    description: 길드 채팅을 활성화 또는 비활성화합니다.
    usage: /길드챗
