name: ReAbility
version: '2.0'
main: org.kkaemok.reAbility.ReAbility
api-version: '1.21'
depend: [LuckPerms, ProtocolLib]

commands:
  능력:
    description: 능력 뽑기 관련 명령어를 사용합니다.
    usage: /능력 <뽑기>
  rtp:
    description: 랜덤 텔레포트를 실행합니다.
    usage: /rtp
  tpa:
    description: 플레이어에게 TPA를 요청합니다.
    usage: /tpa <플레이어|수락|거절>
  길드:
    description: 길드 관리 명령어입니다.
    usage: /길드
  길드챗:
    description: 길드 채팅을 활성화/비활성화합니다.
    usage: /길드챗
